server:
  port: 8083

spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accounts
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





